name = "localpdf"
description = "Serverless PDF Toolkit"

packages = [
    "pypdf",
    "cryptography"
]

[[fetch]]
files = [
    "./core/pdf_merger.py",
    "./core/pdf_splitter.py",
    "./core/pdf_reorder.py"
]
